package vm

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// Console drives the guest's root serial console. It is the bootstrap
// channel used before ADB is reachable (e.g. to enable adbd on TCP) and a
// diagnostic fallback when ADB is down. Output of the whole console is
// mirrored to the VM serial log by QEMU.
type Console struct {
	conn net.Conn

	mu     sync.Mutex // serializes commands
	bufMu  sync.Mutex
	buf    bytes.Buffer
	notify chan struct{}
	closed chan struct{}
	seq    atomic.Int64
}

// NewConsole starts reading from conn.
func NewConsole(conn net.Conn) *Console {
	c := &Console{conn: conn, notify: make(chan struct{}, 1), closed: make(chan struct{})}
	go c.readLoop()
	return c
}

func (c *Console) readLoop() {
	defer close(c.closed)
	b := make([]byte, 4096)
	for {
		n, err := c.conn.Read(b)
		if n > 0 {
			c.bufMu.Lock()
			c.buf.Write(b[:n])
			if c.buf.Len() > 1<<20 { // bound memory: keep the tail
				tail := append([]byte(nil), c.buf.Bytes()[c.buf.Len()-(256<<10):]...)
				c.buf.Reset()
				c.buf.Write(tail)
			}
			c.bufMu.Unlock()
			select {
			case c.notify <- struct{}{}:
			default:
			}
		}
		if err != nil {
			return
		}
	}
}

// Close closes the console connection.
func (c *Console) Close() error { return c.conn.Close() }

var ansiRe = regexp.MustCompile(`\x1b\[[0-9;?]*[A-Za-z]`)

// Run executes a shell command on the console and returns its output and
// exit status. Markers are generated by the shell itself ($((…)) arithmetic)
// so the terminal's echo of the typed command can never be mistaken for them.
func (c *Console) Run(ctx context.Context, cmd string) (string, int, error) {
	if strings.ContainsAny(cmd, "\n\r") {
		return "", -1, fmt.Errorf("console commands must be a single line")
	}
	c.mu.Lock()
	defer c.mu.Unlock()
	n := c.seq.Add(1)
	start := fmt.Sprintf("@@S%d@@", n)
	end := fmt.Sprintf("@@E%d@@", n)
	line := fmt.Sprintf("echo @@S$((%d))@@; %s; echo @@E$((%d))@@ $?\n", n, cmd, n)

	c.bufMu.Lock()
	c.buf.Reset()
	c.bufMu.Unlock()
	if _, err := io.WriteString(c.conn, line); err != nil {
		return "", -1, fmt.Errorf("writing to the Android console: %w", err)
	}
	endRe := regexp.MustCompile(regexp.QuoteMeta(end) + ` (\d+)`)
	for {
		c.bufMu.Lock()
		text := ansiRe.ReplaceAllString(strings.ReplaceAll(c.buf.String(), "\r", ""), "")
		c.bufMu.Unlock()
		if m := endRe.FindStringSubmatchIndex(text); m != nil {
			code, _ := strconv.Atoi(text[m[2]:m[3]])
			out := text[:m[0]]
			if i := strings.LastIndex(out, start); i >= 0 {
				out = out[i+len(start):]
			}
			return strings.Trim(out, "\n"), code, nil
		}
		select {
		case <-ctx.Done():
			return "", -1, fmt.Errorf("the Android console did not answer %q: %w", cmd, ctx.Err())
		case <-c.closed:
			return "", -1, fmt.Errorf("the Android console closed (the VM stopped)")
		case <-c.notify:
		}
	}
}

// WaitShell waits until the console runs commands (Android's console
// service has started). Probes that were typed before the shell existed are
// harmless: each carries its own marker sequence number.
func (c *Console) WaitShell(ctx context.Context) error {
	for {
		pctx, cancel := context.WithTimeout(ctx, 5*time.Second)
		out, code, err := c.Run(pctx, "echo ready")
		cancel()
		if err == nil && code == 0 && strings.Contains(out, "ready") {
			return nil
		}
		if ctx.Err() != nil {
			return fmt.Errorf("the Android console did not become available: %w", ctx.Err())
		}
		select {
		case <-c.closed:
			return fmt.Errorf("the Android console closed (the VM stopped)")
		default:
		}
	}
}
